import os
import re
import getpass
from groq import Groq

class DFChat:
    def __init__(self, df, target=None):
        self.df = df
        self.target = target

        if "GROQ_API_KEY" not in os.environ:
            os.environ["GROQ_API_KEY"] = getpass.getpass("Enter your Groq API key: ")

        self.client = Groq(
            api_key=os.environ.get("GROQ_API_KEY"),
        )

        tipos_colunas = {col: str(tipo) for col, tipo in df.dtypes.items()}
        base = (
            "You are an expert in Exploratory Data Analysis.\n"
            f"You have a dataframe named df with columns and types {tipos_colunas}"
        )

        import math

        desc = df.describe(include='all')
        desc = {
            k: {
                subk: (subv[:50] + "..." if isinstance(subv, str) and len(subv) > 50 else subv)
                for subk, subv in v.items()
                if not (isinstance(subv, float) and math.isnan(subv))
            }
            for k, v in desc.items()
        }

        if target:
            base = base + f" and the target column is {target}"
        base = base + ("\n"
                       f"DataFrame shape is {df.shape}\n"
                       f"Missing values: {df.isnull().sum().to_dict()}\n"
                       f"Some information about the dataset: {desc}\n"
        )

        if df.shape[1] <= 20:
            base = base + f"First 3 rows of the DataFrame:\n"
            for idx, row in df.head(3).iterrows():
                formatted_row = {}
                for col in df.columns:
                    value = row[col]
                    if isinstance(value, str) and len(value) > 50:
                        value = value[:50] + "..."
                    formatted_row[col] = value

                base = base + f"Row {idx} of the DataFrame: {formatted_row}\n"

        base = base + (
                       f"DataFrame may have textual data, take care with df.corr() \n"
                       f"Don't try to load csv, admite that the df is already with the dataframe\n"
                       f"In your codes, replace all print() for display() when are printing DataFrames. For example:\n"
                       f"print('Summary statistics for numerical columns:')\n"
                       f"display(df[['x', 'y', 'z']].describe())\n"
                       f"In your codes, always put a description before results. For example:\n"
                       f"print('Display of missing values:')\n"
                       f"display(df.isnull().sum())\n"
                       f"Before coding, make sure to import the libraries you are going to use\n"
                       f"Preferably use libraries that are always installed\n"
                       f"Always check for the presence of null or categorical values ​​before performing transformations or creating graphs\n"
                       f"Always answer in the same language of the question\n"
                       f"After the codes, never make a Summary of Findings and never show the results.\n"
                       f"Answer only about the dataframe"
        )

        self.system = base

    def chat(self, question, model="meta-llama/llama-4-maverick-17b-128e-instruct"):
        df = self.df.copy()
        chat_completion = self.client.chat.completions.create(
            messages=[
                {
                    "role": "system",
                    "content": f'{self.system}'
                },
                {
                    "role": "user",
                    "content": f"{question}",
                }
            ],
            model=model,
        )

        response = chat_completion.choices[0].message.content
        response = re.sub(r"<think>.*?</think>", "", response, flags=re.DOTALL)

        print('\033[1mImportant: Text generated by AI and may contain incorrect information, always check the content.\033[0m')

        for text in self._separate_text_and_code(response):
            clean_text = self._extract_code(text)
            clean_code = "\n".join(
                [line for line in clean_text.split("\n") if not line.strip().startswith("```")]
            )

            if clean_code != "":
                print(f'\033[1;31m{text}\033[0m')
                try:
                    exec(clean_code)
                except Exception as e:
                    if clean_text.startswith('```python'):
                        print(f"I tried to run the code, but got the following error: {e}")
            else:
                print(text)

        return response

    def _separate_text_and_code(self, texto):
        linhas = texto.split('\n')
        resultado = []
        bloco_texto = []
        bloco_codigo = []
        dentro_do_codigo = False

        for linha in linhas:
            linha_limpa = linha.strip()

            if linha_limpa.startswith('```') and not dentro_do_codigo:
                if bloco_texto:
                    resultado.append('\n'.join(bloco_texto))
                    bloco_texto = []
                dentro_do_codigo = True
                bloco_codigo.append(linha)

            elif linha_limpa.startswith('```') and dentro_do_codigo:
                bloco_codigo.append(linha)
                resultado.append('\n'.join(bloco_codigo))
                bloco_codigo = []
                dentro_do_codigo = False

            else:
                if dentro_do_codigo:
                    bloco_codigo.append(linha)
                else:
                    bloco_texto.append(linha)

        if bloco_texto:
            resultado.append('\n'.join(bloco_texto))

        return resultado

    def _extract_code(self, texto):
        linhas = texto.split('\n')
        dentro_do_codigo = False
        codigo = []

        for linha in linhas:
            linha_limpa = linha.strip()

            if linha_limpa.startswith('```'):
                dentro_do_codigo = True
                codigo.append(linha)
            elif dentro_do_codigo and linha_limpa.startswith('```'):
                codigo.append(linha)
                dentro_do_codigo = False
                break
            elif dentro_do_codigo:
                codigo.append(linha)

        if len(codigo) >= 2:
            inicio = codigo[0]
            fim = codigo[-1]
            linhas_internas = codigo[1:-1]

            indentacoes = []
            for linha in linhas_internas:
                espacos = len(linha) - len(linha.lstrip(' '))
                if espacos > 0 or linha.strip() != '': 
                    indentacoes.append(espacos)

            min_indent = min(indentacoes) if indentacoes else 0

            linhas_ajustadas = [linha[min_indent:] for linha in linhas_internas]

            return '\n'.join([inicio] + linhas_ajustadas + [fim])
        else:
            return '\n'.join(codigo)